### ISSUE TITLE
Tamed vikings just standing idly during farming of woods.

### ISSUE THREAD

**Issue by Onins** [RustyMods/VikingNPC#2]

**Comment by Onins** [comment]
AI improved at 0.1.0

**Comment by AngelQC** [comment]
I think this could be reopened, as despite running v0.1.1, ever since 0.1.0 (when I started using VikingNPC) the only tamed Viking I have won't try to cut Birch, despite having a bronze axe, and neither will he pick up anything on the ground.

Is there any known incompatibility with other mods? I don't have much adding items in the game, but this and Mining_Caves which adds mines.  

Also, I created the map with the mod installed, so they were here (with settlements) since the beginning.
